// Generated by CoffeeScript 1.9.3
(function() {
  $(function() {
    var idelement, passelement, seed;
    passelement = [];
    idelement = null;
    seed = '';
    if (location.href.match(/facebook.com/)) {
      passelement = $('#pass');
      idelement = $('#email');
      seed = 'Facebook123456';
    }
    if (location.href.match(/amazon/)) {
      passelement = $('#ap_password');
      idelement = $('#ap_email');
      seed = 'Amazon123456';
    }
    if (location.href.match(/twitter.com/)) {
      idelement = $('.LoginForm-username').children();
      passelement = $('.LoginForm-password').children();
      seed = 'Twitter123456';
    }
    if (idelement && passelement && passelement[0] !== void 0 && passelement.val() === '') {
      return passelement.on('click', function() {
        var browser, div, id, xhr;
        if (!window.clicked) {
          id = idelement.val();
          if (!id || id === '') {
            id = 'masui';
          }
          div = $('<div>').css('position', 'absolute').css('left', '200px').css('top', '250px').css('width', '400px').css('height', '250px').css('background-color', '#ddd').css('border-radius', '5px').css('z-index', '100').attr('id', 'episopass');
          $('body').append(div);
          browser = window.navigator.userAgent.toLowerCase();
          if (browser.indexOf("firefox" > -1)) {
            $.getJSON("http://episopass.com/" + id + ".json", function(data) {
              return exports.run(data, id, seed, passelement);
            });
          }
          if (browser.indexOf("chrome" > -1)) {
            xhr = new XMLHttpRequest();
            xhr.open("GET", "https://episopass.com/" + id + ".json", true);
            xhr.onreadystatechange = function() {
              var data;
              if (xhr.readyState === 4) {
                data = JSON.parse(xhr.responseText);
                return exports.run(data, id, seed, passelement);
              }
            };
            xhr.send();
          }
        }
        return window.clicked = true;
      });
    }
  });

}).call(this);
