// Generated by CoffeeScript 1.9.3
(function() {
  var a, i, len, ref;

  ref = [10, 20, 30];
  for (i = 0, len = ref.length; i < len; i++) {
    a = ref[i];
    console.log("----" + a + "----");
  }

}).call(this);
