// Generated by CoffeeScript 1.9.3
var Generator, amusement, animals, events, f, freqgo, generator, hasDom, i, j, len, len1, q, questions, recs, schools, search, shops, specialplace, sports, time, ul;

hasDom = require('has-dom');

Generator = require('re_expand');

generator = new Generator();

schools = "(kindergarten|elementary school|middle school|high school)";

time = "(昔|子供のころ|" + schools + "のころ)";

freqgo = "(よく行ってた|行ったことがある|たまに行った)";

shops = "(本屋|床屋|散髪屋|レストラン|食堂|スーパー|市場|八百屋|魚屋|肉屋|店)";

recs = "(旅行|BBQ|バーベキュー)";

sports = "(baseball|football|hiking|climbing|surfing)";

events = "(コンサート|合宿|遠足|花見)";

animals = "(dog|cat|rabbit|rat|hamster)";

amusement = "(the thema park|Disneyland|the zoo)";

specialplace = "(the seashore|the top of the mountain|the shrine|the park|the sandbox)";

questions = ["I had an (pain|injury) when I was going to " + schools + ".", "Bicycle collision", "Tallest person in the " + schools, "I wanted to practice (piano|guitar) when I was going to " + schools + ".", "I want to apologize for ...", "The place I used to enjoy " + sports + " at " + schools, "My (best|worst) score at math", "The person I (hated|liked|loved) in my " + schools + " days.", "The person I loved", "The person who (hated|liked|loved) me", "People who loved each other secretly", "Places I visited when I was going to " + schools, "Scared to death at (mountain|river|lake)", "Car engine stop", "Flat tire", "Lost in the city", "Stolen wallet on a trip", "Couldn't change (trains|buses|subways)", "Broken a bed in a hotel", "No paper in a toilet", "Strange thing at " + amusement, "Terrible hotel", "The restaurant we went very often", "Kind of food I always ate at the restaurant", "Missed event because of circles", "Jellyfish lie", "Blunder at job interview", "Flat tire", "What I hided at the back of the TV", "Hidden an app as a filetype", "Secret place for getting insects", "Worst guy ever", "Always complaining something", "The place I saw a snake", "My first (car|motorcycle|bicycle|guiter|CD|phone|toy)", "First experience of (mountain climbing|camping|going abroad|airplain|bullet train)", "Under the bridge are ...", "Forbidden places", "Found a special thing at " + specialplace, "Yelling at " + specialplace];

for (i = 0, len = questions.length; i < len; i++) {
  q = questions[i];
  generator.add(q);
}

if (hasDom()) {
  ul = null;
  f = function(s, cmd) {
    return ul.append($('<li>').text(s));
  };
  search = function() {
    var qstr;
    if (ul) {
      ul.remove();
    }
    ul = $('<ul>');
    $('body').append(ul);
    qstr = $('#q').val();
    return generator.filter(" " + qstr + " ", f, 0);
  };
  $(function() {
    search();
    return $('#q').on('keyup', search);
  });
} else {
  f = function(a) {
    return console.log(a);
  };
  for (j = 0, len1 = questions.length; j < len1; j++) {
    q = questions[j];
    generator.add(q);
  }
  generator.filter(" ", f);
}
